title: SukHeon Kang # your name (or website title) here
logo: images/ksh.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ksh8048(at)hanyang.ac.kr 
  <br>
  4th year, B.S.
  <br>
  HANYANG UNIV
  <br>
  Seoul, Republic of Korea
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
