title: Sukheon Kang 
logo: images/ksh.jpg 
description: 
  honey_ksh(at)kaist.ac.kr 
  <br>
  1st year, Ph.D.
  <br>
  KAIST
  <br>
  Daejeon, Republic of Korea
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
