title: SukHeon Kang 
logo: images/ksh.jpg 
description: 
  ksh8048(at)hanyang.ac.kr 
  <br>
  4th year, B.S.
  <br>
  HANYANG UNIV
  <br>
  Seoul, Republic of Korea
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
